language: java

services:
  - docker

script:
  - bash name_of_the_script_file

env:
  global:
    - secure: AEUw9aTtBkOWvb/+lRt6WNLdQCoABghkHqOhdII4dYI53hjLtCDfmwEhideGRPFcMu0vFhe6V7/5FgByO9SBfOPXOjIPTgTcGcybO5VPxYQdpjZER50tBCl7RuBAgbMZFTGE8Q6SnTtn/GgltqkDQbxCNhP6RH9kmh34uJlZh5fwit2NU/rHEOO19QyxsbZCsz6LwDCSJdAizhvEks/bTYG9NAvte4kqf9nRwnn/x+V83NtXpfHH/CIr63BR1H0ggOwCn0O3ghQ58xn2HiFWI9I6BdZUCa7nWwPRVcHsH22LIcaHu0AZoUzE4e3CD3d4SgvUSzSP6Wt/tImxoQx6c9RHVd2Xt5UCnGw+rc4RSLhnSd7Q2kMMKeCVagme9lKzfxMWn9ynQl6nVQl1zH+2t8bR9a1IfZVh6aM3deFE10H6v4OvaNfntNf0Tx0RWa+WWuTY8K8T0cj2fQ1abLIy84TE1PXZcmBFZmsCbvdM5kLXO6LSGx9HEtTS2jxfmACjAli2hdvaCWSJON75i3lFYMBMKuIGMo6DEw5brAqkO0tNXmz+SIKuQME8SmUKyZmcSNy3Ydnhfsrj4BWYd/0cuK2lPczfyvbQ7ezD/rLpgIckonVtMmn4BpvVTMkF4vnqcmbTx3hsTUmaem4nayUNu/vxUWj3xkroCtAJBg4mFLI=
    - secure: l/9rD+Znn4Ww3kCz34CXCv0ghxNUFGJiG6NwnFAZB4cAZJfGEz5qT0Am/KM4/tBleAT39Gw0Q/h6EKt5gS+vBIKC9jkU/l5VI9KV9fle9kGQLhAgc3hHbgl8co0MqVPhJfPA4kkSoC1x1xZacatCV1dsP/MXAhwLjd8/mD/b3HmGLo3Hvsxcplx2hEg0I16D48oKJnGi9sC7DyumvtvHXNsowml3lkvkNn/fqUdZAinN7FG4vA82FgB8QfW0MOnQZeVn3za61ZAPOnpahCU4kP66oTDm789lI9LNhlk2RZ+5yDJqcsqqm7fmHCJ+n6I89wOXYJCZO71ZQHAdtanlDhojFJIeLnatwbz/A2lnygLBabVmNBnzmO0OwNDwizMo62odDoS6d7cvi0q4VTY6LQpCMIbh51DCFLoZxPIvr4uVPEUGT5rL1zJF1fRnXM6wgMaHVgd04WllYts3K81XndsjbKzkovwUgHogEZyGtHxfG+fZHzD2AJLgi7Sdn+5Fn5cU+5xAABwviYfqKN9M4bKI24hCFmuD9nOZV10Zol9UQMMNXNUxpGRn7mnA05H0mH82sus9u8xM+NJMTMT3cvsvD6K4QGr6EJRITxY0s/nWGsU7asxFL8bJRkmyRZTGkv4Jsx1GmU7HcbgA8/ypJZKcJpvbALyWrWnxpfuxfuk=
